# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: El blog de Felipe Schneider 
email: felipes (a) gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  SQL Server DBA trabajando en Pyxis 
  Trabajo en SQL Server desde la versión 2005
twitter_username: felipes88
github_username: felipeschneider88
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "default", "dirt", "neon", "mint", "plum" "sunrise"
locale: es-ES
search: true
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
whitelist: [jekyll-analytics]
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-analytics
author:
  name   : "Felipe Schneider"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Me apasionan las bases de datos 🚀 y compartir lo que voy aprendiendo ❤️"
  links:
    - label: "Twitter"
      icon: "fas fa-fw fa-twitter-square"
      url: "https://twitter.com/felipes88"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://blog.includeware.info/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/felipeschneider88"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/felipeschneideruy/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/felipes88"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/felipeschneider88"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/felipeschneideruy/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      comments:
        provider: "disqus"
        disqus:
          shortname: felipes88
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-SCETLP8B1P          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
    
  Matomo:                   # Add, if you want to track with Matomo (former Piwik Analytics)
    url: felipes88.matomo.cloud # Required - url to Matomo installation without trailing /
    siteId: "1"          # Required - replace with your Matomo site id (Write id as string)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-SCETLP8B1P"
    anonymize_ip: false # default